name: Build Dawn (Linux & macOS)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        #os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo bin/ubuntu-packages.sh

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: bin/darwin-packages.sh

      - name: checkout
        run: |
          ./bin/core-checkout.sh

      - name: build
        run: |
          ./bin/core-build.sh

      - name: test
        run: |
          ./bin/core-test.sh

      - name: Archive build
        run: |
          ./bin/core-artifacts.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dawn-webgpu-${{ matrix.os }}
          path: artifacts

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
