name: Build Dawn (Linux & macOS)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        #os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo bin/ubuntu-packages.sh

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: bin/darwin-packages.sh

      - name: checkout
        run: |
          ./bin/core-checkout.sh

      - name: build
        run: |
          ./bin/core-build.sh

      - name: test
        run: |
          ./bin/core-test.sh

      - name: Archive build
        run: |
          mkdir -p artifacts
          cp -r WebGPU-distribution/build artifacts/webgpu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dawn-webgpu-${{ matrix.os }}
          path: artifacts/webgpu
